/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from "react"
import { useGLTF } from "@react-three/drei"
import useRoom from "./store/useRoom.js"
import * as THREE from "three"
import { useGSAP } from "@gsap/react"
import gsap from "gsap"

gsap.registerPlugin(useGSAP)

export default function Rooms(props) {
  const { nodes, materials } = useGLTF("./building_rooms.glb")

  const allRooms = useRef()

  useEffect(() => {
    allRooms.current.traverse((node) => {
      if (node.isMesh) {
        node.visible = false
        node.material = new THREE.MeshStandardMaterial({
          color: "#e75136",
          transparent: true,
          opacity: 0,
        })
      }
    })
  })

  const currentRoomPos = useRoom((state) => state.viewRoomPos)

  useGSAP(() => {
    const unsubscribeRoom = useRoom.subscribe(
      (state) => state.currentRoom,
      (room) => {
        allRooms.current.traverse((node) => {
          if (node.isMesh && node.material.opacity == 1) {
            gsap.to(node.material, {
              opacity: 0,
              onComplete: () => {
                node.visible = false
              },
            })
          }
        })

        if (room) {
          if (room instanceof Array) {
            room.forEach((subRoom) => {
              showRoom(
                allRooms.current.children.find((el) => el.name == subRoom)
              )
            })
            currentRoomPos(
              allRooms.current.children.find((el) => el.name == room[0])
                .position
            )
          } else {
            showRoom(allRooms.current.children.find((el) => el.name == room))
            currentRoomPos(
              allRooms.current.children.find((el) => el.name == room).position
            )
          }
        }
      }
    )

    return () => {
      unsubscribeRoom()
    }
  })

  function showRoom(node) {
    node.visible = true
    node.renderOrder = 0
    gsap.to(node.material, { opacity: 1 })
  }

  return (
    <group {...props} dispose={null} ref={allRooms}>
       <mesh
        name="room_3_03"
        geometry={nodes.room_3_03.geometry}
        material={materials.RoomMaterial}
        position={[-7.804, 4.284, 3.501]}
      />
      <mesh
        name="room_3_06"
        geometry={nodes.room_3_06.geometry}
        material={materials.RoomMaterial}
        position={[-0.498, 4.284, 3.501]}
      />
      <mesh
        name="room_2_04"
        geometry={nodes.room_2_04.geometry}
        material={materials.RoomMaterial}
        position={[-7.842, 0.974, 3.501]}
      />
      <mesh
        name="room_1_02"
        geometry={nodes.room_1_02.geometry}
        material={materials.RoomMaterial}
        position={[-9.594, -2.342, -3.411]}
      />
      <mesh
        name="room_0_04"
        geometry={nodes.room_0_04.geometry}
        material={materials.RoomMaterial}
        position={[-9.594, -5.631, 3.501]}
      />
      <mesh
        name="room_0_01"
        geometry={nodes.room_0_01.geometry}
        material={materials.RoomMaterial}
        position={[-13.318, -5.631, -3.411]}
      />
      <mesh
        name="room_1_03"
        geometry={nodes.room_1_03.geometry}
        material={materials.RoomMaterial}
        position={[-9.594, -2.342, 3.501]}
      />
      <mesh
        name="room_1_04"
        geometry={nodes.room_1_04.geometry}
        material={materials.RoomMaterial}
        position={[-5.859, -2.342, -3.411]}
      />
      <mesh
        name="room_1_07"
        geometry={nodes.room_1_07.geometry}
        material={materials.RoomMaterial}
        position={[-0.489, -2.342, 3.501]}
      />
      <mesh
        name="room_1_06"
        geometry={nodes.room_1_06.geometry}
        material={materials.RoomMaterial}
        position={[-2.279, -2.342, -3.411]}
      />
      <mesh
        name="room_1_08"
        geometry={nodes.room_1_08.geometry}
        material={materials.RoomMaterial}
        position={[1.301, -2.342, -3.411]}
      />
      <mesh
        name="room_1_12"
        geometry={nodes.room_1_12.geometry}
        material={materials.RoomMaterial}
        position={[10.583, -2.342, -3.411]}
      />
      <mesh
        name="room_1_11"
        geometry={nodes.room_1_11.geometry}
        material={materials.RoomMaterial}
        position={[8.828, -2.342, 3.501]}
      />
      <mesh
        name="room_1_13"
        geometry={nodes.room_1_13.geometry}
        material={materials.RoomMaterial}
        position={[12.408, -2.342, 3.501]}
      />
      <mesh
        name="room_1_14"
        geometry={nodes.room_1_14.geometry}
        material={materials.RoomMaterial}
        position={[17.683, -2.342, 0.045]}
      />
      <mesh
        name="room_2_03"
        geometry={nodes.room_2_03.geometry}
        material={materials.RoomMaterial}
        position={[-9.594, 0.974, -3.411]}
      />
      <mesh
        name="room_2_05"
        geometry={nodes.room_2_05.geometry}
        material={materials.RoomMaterial}
        position={[-5.859, 0.974, -3.411]}
      />
      <mesh
        name="room_2_06"
        geometry={nodes.room_2_06.geometry}
        material={materials.RoomMaterial}
        position={[-0.489, 0.974, -3.411]}
      />
      <mesh
        name="room_2_09"
        geometry={nodes.room_2_09.geometry}
        material={materials.RoomMaterial}
        position={[10.618, 0.974, 0.045]}
      />
      <mesh
        name="room_2_12"
        geometry={nodes.room_2_12.geometry}
        material={materials.RoomMaterial}
        position={[17.673, 0.974, 3.501]}
      />
      <mesh
        name="room_2_10"
        geometry={nodes.room_2_10.geometry}
        material={materials.RoomMaterial}
        position={[12.373, 0.974, -3.411]}
      />
      <mesh
        name="room_2_11"
        geometry={nodes.room_2_11.geometry}
        material={materials.RoomMaterial}
        position={[15.848, 0.974, -3.411]}
      />
      <mesh
        name="room_3_11"
        geometry={nodes.room_3_11.geometry}
        material={materials.RoomMaterial}
        position={[19.463, 4.284, -3.411]}
      />
      <mesh
        name="room_3_10"
        geometry={nodes.room_3_10.geometry}
        material={materials.RoomMaterial}
        position={[17.673, 4.284, 3.501]}
      />
      <mesh
        name="room_3_09"
        geometry={nodes.room_3_09.geometry}
        material={materials.RoomMaterial}
        position={[10.61, 4.284, 3.501]}
      />
      <mesh
        name="room_3_08"
        geometry={nodes.room_3_08.geometry}
        material={materials.RoomMaterial}
        position={[12.408, 4.284, -3.411]}
      />
      <mesh
        name="room_3_02"
        geometry={nodes.room_3_02.geometry}
        material={materials.RoomMaterial}
        position={[-9.594, 4.284, -3.411]}
      />
      <mesh
        name="room_3_05"
        geometry={nodes.room_3_05.geometry}
        material={materials.RoomMaterial}
        position={[-0.489, 4.284, -3.411]}
      />
      <mesh
        name="elevator"
        geometry={nodes.elevator.geometry}
        material={materials.RoomMaterial}
        position={[22.126, -2.715, 4.168]}
      />
      <mesh
        name="room_2_08"
        geometry={nodes.room_2_08.geometry}
        material={materials.RoomMaterial}
        position={[5.011, 0.974, -3.411]}
      />
      <mesh
        name="room_1_09"
        geometry={nodes.room_1_09.geometry}
        material={materials.RoomMaterial}
        position={[5.011, -2.342, -3.411]}
      />
      <mesh
        name="room_2_02"
        geometry={nodes.room_2_02.geometry}
        material={materials.RoomMaterial}
        position={[-13.318, 0.974, 3.501]}
      />
      <mesh
        name="room_2_01"
        geometry={nodes.room_2_01.geometry}
        material={materials.RoomMaterial}
        position={[-13.318, 0.974, -3.411]}
      />
      <mesh
        name="room_3_01"
        geometry={nodes.room_3_01.geometry}
        material={materials.RoomMaterial}
        position={[-13.318, 4.284, -3.411]}
      />
      <mesh
        name="room_1_05"
        geometry={nodes.room_1_05.geometry}
        material={materials.RoomMaterial}
        position={[-5.859, -2.342, 3.501]}
      />
      <mesh
        name="room_3_07"
        geometry={nodes.room_3_07.geometry}
        material={materials.RoomMaterial}
        position={[5.011, 4.284, -3.411]}
      />
      <mesh
        name="room_3_04"
        geometry={nodes.room_3_04.geometry}
        material={materials.RoomMaterial}
        position={[-5.859, 4.284, -3.411]}
      />
      <mesh
        name="room_1_01"
        geometry={nodes.room_1_01.geometry}
        material={materials.RoomMaterial}
        position={[-13.318, -2.342, -3.411]}
      />
      <mesh
        name="room_0_02"
        geometry={nodes.room_0_02.geometry}
        material={materials.RoomMaterial}
        position={[-13.318, -5.631, 3.501]}
      />
      <mesh
        name="room_0_08"
        geometry={nodes.room_0_08.geometry}
        material={materials.RoomMaterial}
        position={[5.011, -5.631, -3.411]}
      />
      <mesh
        name="room_0_05"
        geometry={nodes.room_0_05.geometry}
        material={materials.RoomMaterial}
        position={[-5.859, -5.631, -3.411]}
      />
      <mesh
        name="room_0_07"
        geometry={nodes.room_0_07.geometry}
        material={materials.RoomMaterial}
        position={[-0.489, -5.631, 0.045]}
      />
      <mesh
        name="room_0_09"
        geometry={nodes.room_0_09.geometry}
        material={materials.RoomMaterial}
        position={[10.583, -5.631, -3.411]}
      />
      <mesh
        name="room_0_10"
        geometry={nodes.room_0_10.geometry}
        material={materials.RoomMaterial}
        position={[8.828, -5.631, 3.501]}
      />
      <mesh
        name="room_0_11"
        geometry={nodes.room_0_11.geometry}
        material={materials.RoomMaterial}
        position={[14.198, -5.631, 3.501]}
      />
      <mesh
        name="room_0_13"
        geometry={nodes.room_0_13.geometry}
        material={materials.RoomMaterial}
        position={[19.463, -5.631, 3.501]}
      />
      <mesh
        name="room_0_12"
        geometry={nodes.room_0_12.geometry}
        material={materials.RoomMaterial}
        position={[17.648, -5.631, -3.411]}
      />
      <mesh
        name="room_0_06"
        geometry={nodes.room_0_06.geometry}
        material={materials.RoomMaterial}
        position={[-5.859, -5.631, 3.501]}
      />
      <mesh
        name="room_0_03"
        geometry={nodes.room_0_03.geometry}
        material={materials.RoomMaterial}
        position={[-9.594, -5.631, -3.411]}
      />
      <mesh
        name="room_2_07"
        geometry={nodes.room_2_07.geometry}
        material={materials.RoomMaterial}
        position={[-0.498, 0.974, 3.501]}
      />
    </group>
  )
}

useGLTF.preload("./building_rooms.glb")
